version: 1.0.{build}
image: Visual Studio 2017

configuration:
- Debug
- Release

platform: Any CPU

test: off

environment:
  EnableNuGetPackageRestore: true

before_build:
- nuget restore solution\NPOI.sln

build_script:
- for /f "tokens=1,* delims=-" %%a in ('"git describe --tags --long"') do set version_suffix=%%b
- msbuild Solution\vCards.sln /p:VersionSuffix="%version_suffix%-%CONFIGURATION%"

artifacts:
- path: solution\Lib\$(configuration)\*.nupkg
